CREATE PROCEDURE [dbo].[Populate_dbo_AssignedRoles]
AS
BEGIN
/*
	Table's data:    [dbo].[AssignedRoles]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:21:54 PM
	Scripted by:     DESKTOP-S4VLAOQ\Alacer02
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[AssignedRoles]';

IF OBJECT_ID('tempdb.dbo.#dbo_AssignedRoles') IS NOT NULL DROP TABLE #dbo_AssignedRoles;
SELECT [AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID] INTO #dbo_AssignedRoles FROM [dbo].[AssignedRoles] WHERE 0=1;

SET IDENTITY_INSERT #dbo_AssignedRoles ON;

INSERT INTO #dbo_AssignedRoles 
 ([AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID])
SELECT CAST([AssignedRolesID] AS int) AS [AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID] FROM 
(VALUES
	  (1,	48,	'A',	'20180422 12:20:04.927',	1,	5)
	, (2,	48,	'A',	'20180422 12:20:04.937',	1,	6)
	, (3,	48,	'A',	'20180422 12:20:04.940',	1,	7)
	, (4,	48,	'A',	'20180422 12:20:04.943',	1,	8)
	, (5,	48,	'A',	'20180422 12:20:04.943',	1,	9)
	, (6,	48,	'A',	'20180422 12:20:04.947',	1,	10)
	, (7,	48,	'A',	'20180422 12:20:04.950',	1,	11)
	, (8,	48,	'A',	'20180422 12:20:04.950',	1,	12)
	, (9,	48,	'A',	'20180422 12:20:04.953',	1,	13)
	, (10,	48,	'A',	'20180422 12:20:04.953',	1,	14)
	, (11,	3,	'A',	'20180422 12:50:54.013',	1,	15)
	, (13,	48,	'A',	'20180422 14:16:19.247',	1,	47)
	, (14,	4,	'A',	'20180422 14:38:16.117',	1,	49)
) as v ([AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID]);


SET IDENTITY_INSERT #dbo_AssignedRoles OFF;

SET IDENTITY_INSERT [dbo].[AssignedRoles] ON;


WITH cte_data as (SELECT CAST([AssignedRolesID] AS int) AS [AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID] FROM [#dbo_AssignedRoles])
MERGE [dbo].[AssignedRoles] as t
USING cte_data as s
	ON t.[AssignedRolesID] = s.[AssignedRolesID]
WHEN NOT MATCHED BY target THEN
	INSERT ([AssignedRolesID], [AssignToAdmin], [Status], [CreatedOn], [CreatedBy], [RegistrationID])
	VALUES (s.[AssignedRolesID], s.[AssignToAdmin], s.[Status], s.[CreatedOn], s.[CreatedBy], s.[RegistrationID])
WHEN MATCHED THEN 
	UPDATE SET 
	[AssignToAdmin] = s.[AssignToAdmin], [Status] = s.[Status], [CreatedOn] = s.[CreatedOn], [CreatedBy] = s.[CreatedBy], [RegistrationID] = s.[RegistrationID]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[AssignedRoles] OFF;

DROP TABLE #dbo_AssignedRoles;

-- End data of table: [dbo].[AssignedRoles] --
END
GO
