CREATE PROCEDURE [dbo].[Populate_dbo_TimeSheetAuditTB]
AS
BEGIN
/*
	Table's data:    [dbo].[TimeSheetAuditTB]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:21:58 PM
	Scripted by:     DESKTOP-S4VLAOQ\Alacer02
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[TimeSheetAuditTB]';

IF OBJECT_ID('tempdb.dbo.#dbo_TimeSheetAuditTB') IS NOT NULL DROP TABLE #dbo_TimeSheetAuditTB;
SELECT [ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID] INTO #dbo_TimeSheetAuditTB FROM [dbo].[TimeSheetAuditTB] WHERE 0=1;

SET IDENTITY_INSERT #dbo_TimeSheetAuditTB ON;

INSERT INTO #dbo_TimeSheetAuditTB 
 ([ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID])
SELECT CAST([ApprovalTimeSheetLogID] AS int) AS [ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID] FROM 
(VALUES
	  (1,	48,	'20180511 00:58:19.717',	'20180511 00:58:19.707',	'',	1,	1,	47)
	, (2,	48,	'20180511 01:01:51.433',	'20180511 01:01:51.433',	'Approved',	2,	1,	47)
) as v ([ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID]);


SET IDENTITY_INSERT #dbo_TimeSheetAuditTB OFF;

SET IDENTITY_INSERT [dbo].[TimeSheetAuditTB] ON;


WITH cte_data as (SELECT CAST([ApprovalTimeSheetLogID] AS int) AS [ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID] FROM [#dbo_TimeSheetAuditTB])
MERGE [dbo].[TimeSheetAuditTB] as t
USING cte_data as s
	ON t.[ApprovalTimeSheetLogID] = s.[ApprovalTimeSheetLogID]
WHEN NOT MATCHED BY target THEN
	INSERT ([ApprovalTimeSheetLogID], [ApprovalUser], [ProcessedDate], [CreatedOn], [Comment], [Status], [TimeSheetID], [UserID])
	VALUES (s.[ApprovalTimeSheetLogID], s.[ApprovalUser], s.[ProcessedDate], s.[CreatedOn], s.[Comment], s.[Status], s.[TimeSheetID], s.[UserID])
WHEN MATCHED THEN 
	UPDATE SET 
	[ApprovalUser] = s.[ApprovalUser], [ProcessedDate] = s.[ProcessedDate], [CreatedOn] = s.[CreatedOn], [Comment] = s.[Comment], [Status] = s.[Status], [TimeSheetID] = s.[TimeSheetID], [UserID] = s.[UserID]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[TimeSheetAuditTB] OFF;

DROP TABLE #dbo_TimeSheetAuditTB;

-- End data of table: [dbo].[TimeSheetAuditTB] --
END
GO
