CREATE PROCEDURE [dbo].[Populate_dbo_NotificationsTB]
AS
BEGIN
/*
	Table's data:    [dbo].[NotificationsTB]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:21:57 PM
	Scripted by:     DESKTOP-S4VLAOQ\Alacer02
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[NotificationsTB]';

IF OBJECT_ID('tempdb.dbo.#dbo_NotificationsTB') IS NOT NULL DROP TABLE #dbo_NotificationsTB;
SELECT [NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate] INTO #dbo_NotificationsTB FROM [dbo].[NotificationsTB] WHERE 0=1;

SET IDENTITY_INSERT #dbo_NotificationsTB ON;

INSERT INTO #dbo_NotificationsTB 
 ([NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate])
SELECT CAST([NotificationsID] AS int) AS [NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate] FROM 
(VALUES
	  (4,	'D',	'Fill Timesheet',	'20180501 12:02:22.493',	'20180204 09:25:00.000',	'20180204 09:35:00.000')
	, (5,	'D',	'Fill TimeSheet by 5 May',	'20180501 12:48:30.700',	'20180304 09:25:00.000',	'20180304 09:35:00.000')
	, (6,	'D',	'Fill TimeSheet by 1st May',	'20180501 13:41:19.353',	'20180504 09:25:00.000',	'20180504 09:35:00.000')
	, (7,	'D',	'Demo',	'20180501 15:24:31.103',	'20180504 09:25:00.000',	'20180504 09:35:00.000')
	, (8,	'D',	'Welcome',	'20180504 09:20:38.017',	'20180604 09:25:00.000',	'20180604 09:35:00.000')
	, (9,	'A',	'Fill Time Sheet',	'20180504 09:33:52.503',	'20180704 09:30:00.000',	'20180704 09:35:00.000')
) as v ([NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate]);


SET IDENTITY_INSERT #dbo_NotificationsTB OFF;

SET IDENTITY_INSERT [dbo].[NotificationsTB] ON;


WITH cte_data as (SELECT CAST([NotificationsID] AS int) AS [NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate] FROM [#dbo_NotificationsTB])
MERGE [dbo].[NotificationsTB] as t
USING cte_data as s
	ON t.[NotificationsID] = s.[NotificationsID]
WHEN NOT MATCHED BY target THEN
	INSERT ([NotificationsID], [Status], [Message], [CreatedOn], [FromDate], [ToDate])
	VALUES (s.[NotificationsID], s.[Status], s.[Message], s.[CreatedOn], s.[FromDate], s.[ToDate])
WHEN MATCHED THEN 
	UPDATE SET 
	[Status] = s.[Status], [Message] = s.[Message], [CreatedOn] = s.[CreatedOn], [FromDate] = s.[FromDate], [ToDate] = s.[ToDate]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[NotificationsTB] OFF;

DROP TABLE #dbo_NotificationsTB;

-- End data of table: [dbo].[NotificationsTB] --
END
GO
