CREATE PROCEDURE [dbo].[Populate_dbo_Expense]
AS
BEGIN
/*
	Table's data:    [dbo].[Expense]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:21:56 PM
	Scripted by:     DESKTOP-S4VLAOQ\Alacer02
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[Expense]';

IF OBJECT_ID('tempdb.dbo.#dbo_Expense') IS NOT NULL DROP TABLE #dbo_Expense;
SELECT [ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID] INTO #dbo_Expense FROM [dbo].[Expense] WHERE 0=1;

SET IDENTITY_INSERT #dbo_Expense ON;

INSERT INTO #dbo_Expense 
 ([ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID])
SELECT CAST([ExpenseID] AS int) AS [ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID] FROM 
(VALUES
	  (1,	'Demo',	2,	'20180501',	'20180505',	null,	50000,	0,	8000,	0,	0,	0,	0,	58000,	47,	'20180511 00:59:46.627',	'Approved ',	2)
) as v ([ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID]);


SET IDENTITY_INSERT #dbo_Expense OFF;

SET IDENTITY_INSERT [dbo].[Expense] ON;


WITH cte_data as (SELECT CAST([ExpenseID] AS int) AS [ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID] FROM [#dbo_Expense])
MERGE [dbo].[Expense] as t
USING cte_data as s
	ON t.[ExpenseID] = s.[ExpenseID]
WHEN NOT MATCHED BY target THEN
	INSERT ([ExpenseID], [PurposeorReason], [ExpenseStatus], [FromDate], [ToDate], [VoucherID], [HotelBills], [TravelBills], [MealsBills], [LandLineBills], [TransportBills], [MobileBills], [Miscellaneous], [TotalAmount], [UserID], [CreatedOn], [Comment], [ProjectID])
	VALUES (s.[ExpenseID], s.[PurposeorReason], s.[ExpenseStatus], s.[FromDate], s.[ToDate], s.[VoucherID], s.[HotelBills], s.[TravelBills], s.[MealsBills], s.[LandLineBills], s.[TransportBills], s.[MobileBills], s.[Miscellaneous], s.[TotalAmount], s.[UserID], s.[CreatedOn], s.[Comment], s.[ProjectID])
WHEN MATCHED THEN 
	UPDATE SET 
	[PurposeorReason] = s.[PurposeorReason], [ExpenseStatus] = s.[ExpenseStatus], [FromDate] = s.[FromDate], [ToDate] = s.[ToDate], [VoucherID] = s.[VoucherID], [HotelBills] = s.[HotelBills], [TravelBills] = s.[TravelBills], [MealsBills] = s.[MealsBills], [LandLineBills] = s.[LandLineBills], [TransportBills] = s.[TransportBills], [MobileBills] = s.[MobileBills], [Miscellaneous] = s.[Miscellaneous], [TotalAmount] = s.[TotalAmount], [UserID] = s.[UserID], [CreatedOn] = s.[CreatedOn], [Comment] = s.[Comment], [ProjectID] = s.[ProjectID]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[Expense] OFF;

DROP TABLE #dbo_Expense;

-- End data of table: [dbo].[Expense] --
END
GO
