CREATE PROCEDURE [dbo].[Populate_dbo_TimeSheetMaster]
AS
BEGIN
/*
	Table's data:    [dbo].[TimeSheetMaster]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:05:39 PM
	Scripted by:     sa
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[TimeSheetMaster]';

IF OBJECT_ID('tempdb.dbo.#dbo_TimeSheetMaster') IS NOT NULL DROP TABLE #dbo_TimeSheetMaster;
SELECT [TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus] INTO #dbo_TimeSheetMaster FROM [dbo].[TimeSheetMaster] WHERE 0=1;

SET IDENTITY_INSERT #dbo_TimeSheetMaster ON;

INSERT INTO #dbo_TimeSheetMaster 
 ([TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus])
SELECT CAST([TimeSheetMasterID] AS int) AS [TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus] FROM 
(VALUES
	  (1,	'20180506',	'20180512',	35,	47,	'20180511 00:58:19.643',	'Approved',	2)
) as v ([TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus]);


SET IDENTITY_INSERT #dbo_TimeSheetMaster OFF;

SET IDENTITY_INSERT [dbo].[TimeSheetMaster] ON;


WITH cte_data as (SELECT CAST([TimeSheetMasterID] AS int) AS [TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus] FROM [#dbo_TimeSheetMaster])
MERGE [dbo].[TimeSheetMaster] as t
USING cte_data as s
	ON t.[TimeSheetMasterID] = s.[TimeSheetMasterID]
WHEN NOT MATCHED BY target THEN
	INSERT ([TimeSheetMasterID], [FromDate], [ToDate], [TotalHours], [UserID], [CreatedOn], [Comment], [TimeSheetStatus])
	VALUES (s.[TimeSheetMasterID], s.[FromDate], s.[ToDate], s.[TotalHours], s.[UserID], s.[CreatedOn], s.[Comment], s.[TimeSheetStatus])
WHEN MATCHED THEN 
	UPDATE SET 
	[FromDate] = s.[FromDate], [ToDate] = s.[ToDate], [TotalHours] = s.[TotalHours], [UserID] = s.[UserID], [CreatedOn] = s.[CreatedOn], [Comment] = s.[Comment], [TimeSheetStatus] = s.[TimeSheetStatus]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[TimeSheetMaster] OFF;

DROP TABLE #dbo_TimeSheetMaster;

-- End data of table: [dbo].[TimeSheetMaster] --
END
GO
