CREATE PROCEDURE [dbo].[Populate_dbo_Roles]
AS
BEGIN
/*
	Table's data:    [dbo].[Roles]
	Data Source:     [DESKTOP-S4VLAOQ].[TimesheetDB]
	Created on:      4/29/2021 2:21:58 PM
	Scripted by:     DESKTOP-S4VLAOQ\Alacer02
	Generated by:    Data Script Writer - ver. 2.3.0.0
	GitHub repo URL: https://github.com/SQLPlayer/DataScriptWriter/
*/
PRINT 'Populating data into [dbo].[Roles]';

IF OBJECT_ID('tempdb.dbo.#dbo_Roles') IS NOT NULL DROP TABLE #dbo_Roles;
SELECT [RoleID], [Rolename] INTO #dbo_Roles FROM [dbo].[Roles] WHERE 0=1;

SET IDENTITY_INSERT #dbo_Roles ON;

INSERT INTO #dbo_Roles 
 ([RoleID], [Rolename])
SELECT CAST([RoleID] AS int) AS [RoleID], [Rolename] FROM 
(VALUES
	  (1,	'Admin')
	, (2,	'Users')
	, (3,	'SuperAdmin')
) as v ([RoleID], [Rolename]);


SET IDENTITY_INSERT #dbo_Roles OFF;

SET IDENTITY_INSERT [dbo].[Roles] ON;


WITH cte_data as (SELECT CAST([RoleID] AS int) AS [RoleID], [Rolename] FROM [#dbo_Roles])
MERGE [dbo].[Roles] as t
USING cte_data as s
	ON t.[RoleID] = s.[RoleID]
WHEN NOT MATCHED BY target THEN
	INSERT ([RoleID], [Rolename])
	VALUES (s.[RoleID], s.[Rolename])
WHEN MATCHED THEN 
	UPDATE SET 
	[Rolename] = s.[Rolename]
WHEN NOT MATCHED BY source THEN
	DELETE
;

SET IDENTITY_INSERT [dbo].[Roles] OFF;

DROP TABLE #dbo_Roles;

-- End data of table: [dbo].[Roles] --
END
GO
